#!/bin/bash
out=$1
jupyter nbconvert --TagRemovePreprocessor.enabled=True \
                  --TagRemovePreprocessor.remove_cell_tags="['hide']" \
                  --TemplateExporter.exclude_input=True --to ${out} black_nichols.ipynb --template=fmvtemplate.tplx 
